// ═══════════════════════════════════════════════════════════════
//  ELBA DUNGEON - ENEMY / NPC DATA
//  admin.html에서 대사/스탯 편집 가능
// ═══════════════════════════════════════════════════════════════

const ENEMIES = {
  // ── 1층: 숲의 입구 (팀원급) ──
  kcy:  { name: '김채영',   title: '편집의 정령',       team: '컨텐츠1팀', role: '팀원',
          hp: 35, atk: 18, def: 4,  exp: 12, skill: '빠른 컷 편집',
          intro: '"이 숲의 영상은 내가 다듬는다."',
          defeat: '"이런... 다음엔 더 날카롭게 편집해올게."' },
  ngk:  { name: '남궁기찬', title: '모션의 마법사',     team: '컨텐츠1팀', role: '팀원',
          hp: 40, atk: 20, def: 3,  exp: 14, skill: '모션그래픽 폭풍',
          intro: '"움직이지 않는 건 아무 의미가 없지."',
          defeat: '"멋진 움직임이었어... 인정할게."' },
  gmj:  { name: '감민진',   title: '채널의 수호자',     team: '컨텐츠1팀', role: '팀원',
          hp: 38, atk: 17, def: 5,  exp: 12, skill: '채널 운영 회오리',
          intro: '"신입이라고? 이 채널은 그리 호락호락하지 않아."',
          defeat: '"후... 적응이 빠르네. 같이 일하면 재밌겠다."' },
  yhr:  { name: '윤하린',   title: '빛의 궁수',         team: '컨텐츠1팀', role: '팀원',
          hp: 32, atk: 19, def: 3,  exp: 11, skill: '빛나는 화살',
          intro: '"궁금한 건 많은데, 일단 실력부터 보여줘!"',
          defeat: '"이야, 대단한데? 앞으로 편하게 물어봐!"' },
  nsh:  { name: '노수현',   title: '다큐의 서기관',     team: '컨텐츠2팀', role: '팀원',
          hp: 36, atk: 18, def: 5,  exp: 13, skill: '다큐 연대기',
          intro: '"기록은 곧 힘이다. 네 힘을 보여봐."',
          defeat: '"보람 있는 싸움이었어. 화이팅!"' },

  // ── 2층: 어둠의 회랑 (팀원급 강화) ──
  lj:   { name: '이준',     title: '대본의 현자',       team: '컨텐츠2팀', role: '팀원',
          hp: 48, atk: 22, def: 6,  exp: 18, skill: '서사의 구속',
          intro: '"이 회랑의 이야기는 내가 쓴다."',
          defeat: '"좋은 줄거리였어. 다음 에피소드에서 보자."' },
  gyh:  { name: '구예희',   title: '기획의 점술사',     team: '컨텐츠2팀', role: '팀원',
          hp: 45, atk: 21, def: 7,  exp: 17, skill: '기획안 결계',
          intro: '"기획 없는 전투는 패배할 뿐이야."',
          defeat: '"네 기획력, 인정할게."' },
  cis:  { name: '최인실',   title: '장비의 연금술사',   team: '컨텐츠2팀', role: '팀원',
          hp: 50, atk: 20, def: 8,  exp: 18, skill: '촬영 장비 소환',
          intro: '"이 회랑의 장비는 내가 관리한다!"',
          defeat: '"OJT에서 또 만나자. 장비 다루는 법 알려줄게."' },
  pjy:  { name: '박준영',   title: '편집의 기사',       team: '컨텐츠2팀', role: '팀원',
          hp: 52, atk: 24, def: 5,  exp: 19, skill: '프리미어 참격',
          intro: '"영상 편집은 전투와 같다. 컷 하나가 승부를 가른다."',
          defeat: '"좋은 편집이었어. 질문 있으면 환영."' },
  lhy:  { name: '이하영',   title: '파이프라인의 마녀', team: '컨텐츠2팀', role: '팀원',
          hp: 46, atk: 22, def: 6,  exp: 17, skill: '제작 파이프라인 저주',
          intro: '"파이프라인을 모르면 여기서 헤어나지 못해."',
          defeat: '"금방 익숙해질 거야. 걱정 마."' },
  pjs:  { name: '박준식',   title: 'NAS의 수호기사',   team: '컨텐츠2팀', role: '팀원',
          hp: 55, atk: 21, def: 9,  exp: 20, skill: 'NAS 폴더 미궁',
          intro: '"이 회랑의 폴더 구조를 헤쳐나갈 수 있을까?"',
          defeat: '"처음엔 복잡하지만, 금방 익혀. 3회 로그인 실패만 조심해!"' },

  // ── 3층: 불의 전당 (팀장급) ──
  kjy:  { name: '김지영',   title: '숏폼의 여왕',       team: '컨텐츠1팀', role: '팀장',
          hp: 80, atk: 28, def: 10, exp: 35, skill: '1분의 한계돌파',
          intro: '"1분이면 충분하다. 네 실력을 보여줘."',
          defeat: '"1분의 한계가 없음을 증명했구나. 대단해."' },
  lth:  { name: '이태환',   title: '밀리터리의 장군',   team: '컨텐츠2팀', role: '팀장',
          hp: 85, atk: 30, def: 9,  exp: 38, skill: '밀리터리 지식 포격',
          intro: '"밀리터리 콘텐츠의 1인자 자리는 내놓지 않는다!"',
          defeat: '"이런 콘텐츠가 이렇게 재밌는 줄 몰랐을 거야. 환영한다."' },
  lmk:  { name: '이민기',   title: '코드의 대마법사',   team: '개발팀',   role: '팀장',
          hp: 75, atk: 27, def: 12, exp: 36, skill: 'YouViCo 시스템 전개',
          intro: '"피드백을 넘어 AI가 직접 수정한다. 이것이 미래다."',
          defeat: '"막히면 말해. 개발 환경 세팅 도와줄게."' },
  lsh:  { name: '임성훈',   title: '자동화의 대사제',   team: '경영지원실', role: '팀장',
          hp: 70, atk: 26, def: 11, exp: 34, skill: 'Zapier 연쇄 자동화',
          intro: '"90%까지 자동화하는 게 내 목표다. 남은 10%는 네가 채워."',
          defeat: '"온보딩 담당자로서 말할게. 잘 왔어."' },

  // ── 4층: 얼음의 심연 (이사급 + 개발팀) ──
  hbw:  { name: '홍병우',   title: '사업의 현자',       team: '운영',     role: '이사',
          hp: 100, atk: 35, def: 14, exp: 50, skill: '사업 전략 빙결',
          intro: '"사업을 이해하지 못하면 이 심연을 건널 수 없다."',
          defeat: '"궁금한 게 있으면 언제든 물어봐. 동료니까."' },
  kdh:  { name: '김대훈',   title: '운영의 빙제',       team: '운영',     role: '이사',
          hp: 105, atk: 34, def: 15, exp: 52, skill: '운영 시스템 동결',
          intro: '"모든 것이 원활하게 돌아가도록 하는 것, 그것이 운영이다."',
          defeat: '"잘 적응하고 있군. 이슈 있으면 편하게 연락해."' },
  jsb:  { name: '조성빈',   title: '코드 리뷰의 심판관', team: '개발팀',  role: '팀장대리',
          hp: 65, atk: 28, def: 10, exp: 30, skill: '꼼꼼한 코드 리뷰',
          intro: '"코드 리뷰는 꼼꼼하게. 이것이 성장의 길이다."',
          defeat: '"같이 성장하자. 좋은 코드란 건 결국 팀의 합작이야."' },
  hmh:  { name: '홍명헌',   title: '환경 세팅의 기사',   team: '개발팀',  role: '팀원',
          hp: 55, atk: 25, def: 8,  exp: 25, skill: '개발환경 초기화',
          intro: '"환경이 안 돌아가면 아무것도 못 해. 기본이 중요하지."',
          defeat: '"세팅에서 막히면 말해. 도와줄게."' },

  // ── 5층: 왕좌의 방 (최종 보스) ──
  gjw:  { name: '구주원',   title: '미디어의 왕',       team: 'ELBA',     role: '대표',
          hp: 200, atk: 40, def: 16, exp: 100, skill: 'CEO Letter 각성',
          intro: '"ELBA is ABLE. 네가 그것을 증명할 차례다."',
          defeat: '"잘 왔다, 탐험가여. 너는 이제 우리 중 하나다. 앞으로 잘 부탁한다."',
          isBoss: true },

  // ── 기타 NPC (비전투) ──
  bgy:  { name: '변가윤',   title: '디자인의 요정',     team: '브랜드경험팀', role: '팀원',
          isShopkeeper: true,
          shopLine: '"여행자여, 필요한 것이 있나? Figma의 힘으로 만든 아이템들이야."',
          shopItems: ['potion', 'scroll'] },
  kmj:  { name: '김미진',   title: '회복의 사제',       team: '경영지원실', role: '팀원',
          isHealer: true,
          healLine: '"쉬어가렴. FLEX로 출퇴근 관리하듯, 체력 관리도 중요하단다."' },
  kth:  { name: '김태호',   title: '정보의 학자',       team: '경영지원실', role: '팀원',
          isInfoNpc: true,
          infoLine: '"이 던전에 대해 알고 싶은 게 있나? 경영지원 쪽 업무가 궁금하면 알려줄게."' },
  kkb:  { name: '김규빈',   title: '지원의 연금술사',   team: '경영지원실', role: '팀원',
          isInfoNpc: true,
          infoLine: '"지원사업 관련 작업이 꽤 많아. 같이 해보자."' },
};

// 팀별 색상
const TEAM_COLORS = {
  'ELBA': '#e8a025',
  '운영': '#e8a025',
  '개발팀': '#9060d0',
  '브랜드경험팀': '#d0a030',
  '컨텐츠2팀': '#d04040',
  '컨텐츠1팀': '#4080d0',
  '경영지원실': '#40b060',
};
